spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userservice-route
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${GATEWAYSERVICE_DATASOURCE_URL}
    username: ${GATEWAYSERVICE_DATASOURCE_USERNAME}
    password: ${GATEWAYSERVICE_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      types:
        registration: hypersistence-utils
        json-dialect: true
    show-sql: false
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

github:
  username: ${GITHUB_USERNAME}
  token: ${GITHUB_TOKEN}

cache:
  memory:
    maxSize: 1000000000