spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userservice-route
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
        - id: emailservice-route
          uri: lb://EMAILSERVICE
          predicates:
            - Path=/emailservice/**

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

github:
  username: ${GITHUB_USERNAME}
  token: ${GITHUB_TOKEN}

cache:
  memory:
    maxSize: 1000000000