spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userservice-route
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**

  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgresql_user-service:5432/GatewayServiceDB
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      types:
        registration: hypersistence-utils
        json-dialect: true
    show-sql: false
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  data:
    redis:
      host: redis
      port: 6379

  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

github:
  username: ${GITHUB_USERNAME}
  token: ${GITHUB_TOKEN}

cache:
  memory:
    maxSize: 1000000000

security:
  jwt:
    secret: secret