### Authenticate as Existing User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "Password123!"
}

### Authenticate as Guest
POST {{ baseUrl }}/auth/loginAsGuest
Content-Type: : application/json

> {%
    client.global.set("token", response.body.accessToken)
    console.log("Token: " + response.body.accessToken)
    console.log("Token saved to global variable 'token': " + client.global.get("token"))
%}
