### Authenticate as Existing User
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "Password123!"
}

### Authenticate as Guest
POST {{ baseUrl }}/auth/loginAsGuest
Content-Type: : application/json

> {% token = response.body.accessToken %}
