### Create a New Super Admin
POST {{baseUrl}}/user-service/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entityClassName": "User",
  "properties": {
    "username": "firstSuperAdmin",
    "userRole": "SUPER_ADMIN",
    "password": "SuperSecurePassword123!"
  }
}

> {%
    console.log(request.headers);
    console.log(response.body);
%}