### Create first Super Admin
POST {{baseUrl}}/user-service/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entityClassName": "User",
  "properties": {
    "username": "firstSuperAdmin",
    "userRole": "SUPER_ADMIN",
    "password": "SuperSecurePassword123!"
  }
}

> {%
    console.log(request.headers);
    console.log(response.body);
%}

### Create second Super Admin
POST {{baseUrl}}/user-service/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entityClassName": "User",
  "properties": {
    "username": "secondSuperAdmin",
    "userRole": "SUPER_ADMIN",
    "password": "SuperSecurePassword123!"
  }
}

> {%
    console.log(request.headers);
    console.log(response.body);
%}

### Create third Super Admin
POST {{baseUrl}}/user-service/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entityClassName": "User",
  "properties": {
    "username": "thirdSuperAdmin",
    "userRole": "SUPER_ADMIN",
    "password": "SuperSecurePassword123!"
  }
}

### Create fourth Super Admin (should fail)
POST {{baseUrl}}/user-service/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "entityClassName": "User",
  "properties": {
    "username": "fourthSuperAdmin",
    "userRole": "SUPER_ADMIN",
    "password": "SuperSecurePassword123!"
  }
}

> {%
    console.log(request.headers);
    console.log(response.body);
%}